await fetch("https://api.github.com/repos/vilking1996/sohong/dispatches", {
  method: "POST",
  headers: {
    "Accept": "application/vnd.github+json",
    "Authorization": `Bearer ${webhookToken}`,
  },
  body: JSON.stringify({
    event_type: "update_balance",
    client_payload: {
      name: acc.name,
      balance: parseFloat(acc.balance).toLocaleString("en-US", {minimumFractionDigits:2}),
      history: acc.history // toàn bộ lịch sử
    }
  })
});
